# Generated by Django 2.2.3 on 2019-07-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='like',
            field=models.BooleanField(default=None),
        ),
    ]
