# Generated by Django 2.2.3 on 2019-07-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_artist_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='like',
        ),
        migrations.AddField(
            model_name='song',
            name='song_likes',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
    ]
