# Generated by Django 2.2.3 on 2019-07-25 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_auto_20190717_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artist_song',
            field=models.FileField(blank=True, upload_to='mp3'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='landing.Artist'),
        ),
    ]
